### PR TITLE
Swapped in standard logging library.

### PR DESCRIPTION
**Pull request by BlackVegetable**
I also added spaces after commas. I'm assuming the other pattern was
an oversight but if not: sorry.

I'm hoping you will have an image we can use to test this on. Cause otherwise this will get painful.

### CODE REVIEW

**Comment by BlackVegetable** [comment]
Solves #12

**Review by earlye — APPROVED** [review]
LGTM

**Comment by earlye** [comment]
Commas - I don't have any strong preference there. Happy to have spaces after them or not.

**Comment by BlackVegetable** [comment]
This is still untested though. So once you have an image, I expect I'll need to do some cleanup.

**Comment by stevenuray** [comment]
Was going to review this, but saw Early did, so I am not going to unless you guys think it's a good idea.

**Comment by BlackVegetable** [comment]
It isn't tested though. So please do that.

**Pull request merged**
